server:
  port: 8088
spring:
  datasource:
    url: jdbc:h2:./db/emdb
    username: htwo
    password: htwo
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true