### Save

POST http://{{host}}:{{port}}/{{root}}/{{locations}}
Accept: application/json
Content-Type: application/json

{
  "note": "Some comment",
  "shelf": {
    "name": "#1"
  },
  "shelving": {
    "name": "#1"
  },
  "library": {
    "name": "Central Library N.V. Gogol"
  }
}

### Get

GET http://{{host}}:{{port}}/{{root}}/{{locations}}/196
Accept: application/json

### Update

PUT http://{{host}}:{{port}}/{{root}}/{{locations}}/196
Accept: application/json
Content-Type: application/json

{
  "note": "Another comment",
  "shelf": {
    "id": 193,
    "name": "#1"
  },
  "shelving": {
    "id": 194,
    "name": "#1"
  },
  "library": {
    "id": 195,
    "name": "Central Library N.V. Gogol"
  }
}

### Delete

DELETE http://{{host}}:{{port}}/{{root}}/{{locations}}/1

### Search

POST http://{{host}}:{{port}}/{{root}}/{{locations}}/search
Accept: application/json
Content-Type: application/json

{
  "page": "0",
  "size": "10"
}

###