### Save

POST http://{{host}}:{{port}}/{{root}}/{{locations}}
Accept: application/json
Content-Type: application/json

{
  "note": "Some comment",
  "shelf": {
    "name": "#1"
  }
}

### Get

GET http://{{host}}:{{port}}/{{root}}/{{locations}}/1
Accept: application/json

### Update

PUT http://{{host}}:{{port}}/{{root}}/{{locations}}/1
Accept: application/json
Content-Type: application/json

{
  "note": "Another comment"
}

### Delete

DELETE http://{{host}}:{{port}}/{{root}}/{{locations}}/1

### Search

POST http://{{host}}:{{port}}/{{root}}/{{locations}}/search
Accept: application/json
Content-Type: application/json

{
  "page": "0",
  "size": "10"
}

###