### Save

POST http://{{host}}:{{port}}/{{root}}/{{shelving}}
Accept: application/json
Content-Type: application/json

{
  "name": "#1"
}

### Get

GET http://{{host}}:{{port}}/{{root}}/{{shelving}}/1
Accept: application/json

### Update

PUT http://{{host}}:{{port}}/{{root}}/{{shelving}}/1
Accept: application/json
Content-Type: application/json

{
  "name": "#2"
}

### Delete

DELETE http://{{host}}:{{port}}/{{root}}/{{shelving}}/1

### Search

POST http://{{host}}:{{port}}/{{root}}/{{shelving}}/search
Accept: application/json
Content-Type: application/json

{
  "page": "0",
  "size": "10"
}

###